### ISSUE TITLE
'socket hang up' error thrown randomly

### ISSUE THREAD

**Issue by revett** [netlify/cli#404]
**- Do you want to request a *feature* or report a *bug*?**

Bug

**- What is the current behavior?**

At points during development the following error occurs which stops the entire Netlify Dev stack:

```
.../node_modules/netlify-redirector/lib/redirects.js:116
      throw ex;
      ^

Error: socket hang up
    at createHangUpError (_http_client.js:323:15)
    at Socket.socketCloseListener (_http_client.js:364:25)
    at Socket.emit (events.js:194:15)
    at TCP._handle.close (net.js:600:12)
```

Looks like it was also reported on the community forum back in April - https://community.netlify.com/t/netlify-dev-regularly-crashes/551

**- If the current behavior is a bug, please provide the steps to reproduce.**

I haven't been able see any common pattern for what causes this. 

**- What is the expected behavior?**

Should not crash. 

**- Please mention your node.js, and operating system version.**

- Node: `v10.15.1`
- Using `yarn`
- Netlify CLI `2.12.0`

**Comment by akramsaouri** [comment]
Been happening to me too.
I'm using [CRAL](https://github.com/netlify/create-react-app-lambda) with  [graphql-yoga](https://github.com/prisma/graphql-yoga/tree/master/examples/lambda-netlify), any updates?

**Comment by dustb0wl** [comment]
+1 - I've had the same issue

**Comment by pushred** [comment]
It's also worth noting that with CRA at least it's processes remain running after the crash and must be killed. 

```
99970 ttys000    0:00.14 /Users/example/.nvm/versions/node/v10.15.3/bin/node /Users/example/dev/node_modules/.bin/react-scripts start
99971 ttys000    0:12.25 /Users/example/.nvm/versions/node/v10.15.3/bin/node /Users/example/dev/node_modules/react-scripts/scripts/start.js
```

**Comment by zslabs** [comment]
Adding onto what @pushred mentioned above; it'd be great if the port could also be shut-down in the event an error is caught - re-googling `sudo lsof -i tcp:3000` and `kill -QUIT <PID>` is sadly something I will never memorize and is the bane of my existence.

**Comment by DomVinyard** [comment]
yes, I'm getting this repeatedly, every edit almost

**Comment by leibovic** [comment]
This has been happening to me as well. It looks like netlify-redirector isn't open source, so it isn't even possible to try to debug the root of the issue.

**Comment by nonissue** [comment]
Yah, I'm getting this as well. For anyone on mac, if you don't have any other node processes running, `killall node` saves me from having to use `lsof`. Use it with caution though obviously.

**Comment by samblacklock** [comment]
Also seeing this all the time, both on build and on file changes. We invested quite a bit of time into refactoring our frontend to run completely on `netlify dev` so this is really frustrating! We are running an Ember.js app with a bunch of netlify functions

One thing we have noticed is that using Chrome in particular triggers this error where other browsers don't seem to...

**Comment by pachiraDIG** [comment]
I'm actually getting the error almost constantly using Firefox, so its not just a Chrome issue.
I can't seem to narrow down the cause.

May I ask why this hasn't been given attention since August?

**Comment by pachiraDIG** [comment]
@raeesbhatti @sw-yx

**Comment by raeesbhatti** [comment]
This is high on my priority list but I haven't able to reproduce it because it is not consistent. It would be greatly helpful if you can share any of your repos that have this issue more often. I've tried this on macOS, is it more common on other OS'es?
Also, in the meantime, we pushed a change recently that cleans up the CRA-like server processes when the Netlify Dev crashes. Please provide feedback on that issue here: https://github.com/netlify/cli/issues/580

**Comment by dustb0wl** [comment]
@raeesbhatti For what it's worth, I was getting it consistently and frequently in Jekyll projects on MacOS, even when it was freshly generated.  I haven't used it in a few months, but I can try and reproduce again.  Did not seem to be browser specific in my experience.

**Comment by therobinkim** [comment]
@raeesbhatti So far, I figured out a reliable way to recreate socket hang up errors only on the _initial_ run of `netlify dev`, but I'm hoping this offers us some breadcrumbs.

1. Set up a new Ionic React project https://ionicframework.com/docs/react/your-first-app (this probably isn't unique to Ionic or React, but it's what my project is based on, and what I used to reproduce `socket hang up` errors)
  a. `npm install -g ionic`
  b. `ionic start`
  c. Provide a name, select `react`, select `sidemenu`
  d. `cd` into the newly created directory
2. Run `netlify dev`, then immediately go do weird things with localhost:8888 in the browser. What I mean by that:
  a. Run `netlify dev`, then as soon as browser opens localhost:8888, close the browser tab => socket hang up error
  b. OR have localhost:8888 already open in another tab, run `netlify dev`, and spam the refresh button on the existing localhost:8888 tab (while the new localhost:8888 tab is popping up) => socket hangup error

One thing I HAVE noticed before is that once I get a socket hangup error, I seem to get a bunch of them in a row (where I'm unable to run `netlify dev` for like 5-10 min straight). This makes me wonder...
* since `netlify dev` opens a new browser tab for localhost:8888 every time
* and my browser is autorefreshing existing, old tabs for localhost:8888
...if I don't close the old tabs, am I essentially experiencing the behavior outlined in (2b) above?

And if so, is something similar happening if I have multiple browser tabs opened for localhost:8888?

...the mystery continues!

**Comment by pachiraDIG** [comment]
@raeesbhatti I have the problem in Windows, so with @dustb0wl 's input, it seems to be cross-platform.

I have the same issue as above, from time to time. Closing (and sometimes refreshing) the browser tab does sometimes trigger the socket hang up. But the majority of the time, for me, it happens while just sitting there between making changes to code.

**Comment by jajouka79** [comment]
until this is fixed it seems that Netlify Dev is unusable for me. i am having the same issue, either in the browser or postman i can call a function one time then the server dies with this same message .

heres an example function endpoint :

localhost:8888/.netlify/functions/login

im using macos

**Comment by iwazaru** [comment]
I'm experimenting the same crash on macOS (`netlify-cli/2.30.0 darwin-x64 node-v12.10.0`), running a react app.

Note that if you're like me and find that Netlify Dev opening a new browser tab every time it restarts is annoying (and thus closing the tab immediately, causing Netlify Dev to crash), you can set the
`autoLaunch` param to `false` in your `netlify.toml` file's `[dev]` block to prevent this behavior.

```toml
[dev]
  autoLaunch = false
```

**Comment by mrlubos** [comment]
Running into this issue since forever, too. It's not consistent at all. For all I know, it happens when I save a change which triggers a reload, and then do something during the reload that causes the error to throw. Might be completely wrong though, it's just my hypothesis that appears to work, i.e. avoid seeing this error more often. 😆 

```
/Users/mrlubos/.nvm/versions/node/v12.14.1/lib/node_modules/netlify-cli/node_modules/netlify-redirector/lib/redirects.js:116
      throw ex;
      ^

Error: socket hang up
    at connResetException (internal/errors.js:570:14)
    at Socket.socketCloseListener (_http_client.js:380:25)
    at Socket.emit (events.js:228:7)
    at Socket.EventEmitter.emit (domain.js:475:20)
    at TCP.<anonymous> (net.js:664:12) {
  code: 'ECONNRESET'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 7
```

**Comment by zslabs** [comment]
@mrlubos Saves during reload causing the error has been my experience as well.

**Comment by miohtama** [comment]
I am launching Eleventy server `eleventy --serve` through `netlify dev`.

I noticed there are lingering BrowserSync, node watch and server processes. To get rid of them do:

```sh
pkill -f eleventy
```

Then I disabled BrowserSync in `eleventy.js`, disabled autolaunch

```
[dev]
  command = "npm run start"
  autoLaunch = false
```

This should not cause extra background processes to appear. 

I think it might be caused by some kind of race condition with file watching and autoreload, but this is just a hunch.

**Comment by miohtama** [comment]
Here is my workaround.

Use `netlify-lambda` instead of Netlify dev server.

1. In one terminal start Lambda

```npx netlify-lambda serve src/functions``` 

It will listen for API function calls in localhost:9000.

2. In another port start `npx eleventy --serve`. It will listen to the page request in localhost:8080.

3. In all your source files, have a switch between `prod` and `env` that will write API function URLs differently depending are you running them locally or not.

**Comment by jarkin13** [comment]
I tried using `netlify-lambda` and although this definitely does not crash as often and when it does I don't need to recompile my entire react project every time. However, there are a lot more items you need to reconfigure. 

1.  I needed to move my functions
2. ENV variables from your netlify project are no longer available. I spent 30 minutes trying to figure it out and moved on
3. Then you need to ensure all paths are fixed

I really just want to develop without netlify crashing every single time I reload my browser. Are there any progress on what to do?

**Comment by christopheragnus** [comment]
Any updates on resolving this?

**Comment by christopheragnus** [comment]
EDIT: tested this on Node 12, and it seems to only happen on Node 13.

**Comment by drzax** [comment]
There's some chance this is a different problem, but I was running into similar issues. 

```
/project/node_modules/netlify-redirector/lib/redirects.js:116
      throw ex;
      ^

Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at write_ (_http_outgoing.js:594:17)
    at ServerResponse.write (_http_outgoing.js:586:15)
    at /project/node_modules/netlify-cli/src/utils/serve-functions.js:163:18
    at /project/functions/volunteer.js:34:9
    at /project/node_modules/googleapis-common/build/src/apirequest.js:43:53
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Emitted 'error' event on ServerResponse instance at:
    at writeAfterEndNT (_http_outgoing.js:649:7)
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  code: 'ERR_STREAM_WRITE_AFTER_END'
}
```
and

```
⢀ Building development bundle/project/node_modules/netlify-redirector/lib/redirects.js:116
      throw ex;
      ^

Error: socket hang up
    at connResetException (internal/errors.js:570:14)
    at Socket.socketCloseListener (_http_client.js:380:25)
    at Socket.emit (events.js:215:7)
    at TCP.<anonymous> (net.js:659:12) {
  code: 'ECONNRESET'
}
```

The latter seemed to occur when I was too quick to refresh the function invocation after restarting `netlify dev`. 

The error, in the end, looks like being that I was calling a callback function from an async handler. The line https://github.com/netlify/cli/blob/aea57cb0d06b7341cd72f4aaa361cefbc370be9f/src/utils/serve-functions.js#L122 is what tipped me off to the issue.

**Comment by erquhart** [comment]
For anyone watching this, it's now top priority 👍 Updates soon.

**Comment by PerrySetGo** [comment]
this thread in Community should also be updated when we have a fix. Thanks @erquhart .

https://community.netlify.com/t/error-socket-hang-up-is-there-a-cure-for-random-socket-errors/9586/2

**Comment by mysteryihs** [comment]
Also getting this error frequently. Using https://github.com/netlify-templates/gatsby-starter-netlify-cms and it often corrupts the .cache directory. Have to manually run `gatsby clean` and kill node processes before I can run `netlify dev`

**Comment by RaeesBhatti** [comment]
We've discovered a cure-all [fix for this problem](https://github.com/netlify/cli/pull/733). And it is in the pipeline to be released soon. Please hold on.

**Comment by RaeesBhatti** [comment]
We've just published a new version (2.37.0). Please update and let us know if it works for you.

**Comment by loic294** [comment]
The fix seems to be working for me! Thanks!

**Comment by abtx** [comment]
Same problem, but only in deployment. It happens every now and then, and never in dev. I need to ship my app and this is a deal breaker atm. Help!

**Comment by zb2oby** [comment]
hello,
Same problem with faunadb request after deployment on src change
`request to https://db.fauna.com/ failed, reason: socket hang up`

**Comment by t2ca** [comment]
This issue still exists.
`GraphQL error: request to https://db.fauna.com/ failed, reason: socket hang up`

**Comment by kremenhero** [comment]
@abtx @zb2oby @t2ca not sure about your case, but maybe this link can help you - https://github.com/netlify/netlify-faunadb-example/issues/15.

**Comment by t2ca** [comment]
> @abtx @zb2oby @t2ca not sure about your case, but maybe this link can help you - [netlify/netlify-faunadb-example#15](https://github.com/netlify/netlify-faunadb-example/issues/15).

Thank you @kremenhero

**Comment by traianrdev6** [comment]
I am still seeing this issue constantly and I am on netlify cli version 2.52.0. It makes netlify dev basically unusable for me. My node version is 12.18.0

netlify -v
netlify-cli/2.52.0 darwin-x64 node-v12.18.0

error while proxying request: socket hang up
/Users/user/.config/yarn/global/node_modules/netlify-redirector/lib/redirects.js:116
      throw ex;
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}
error Command failed with exit code 7.

**Comment by erquhart** [comment]
@RaeesBhatti seems this needs another look.

**Comment by lkundesu** [comment]
Any solution for this?

**Comment by ricvillagrana** [comment]
Same issue here.
Details:
```
OS: macOS 10.15.4
Node version: 10.21.0 (also tried with 12.8.0)
Netlify CLI: netlify-cli/2.54.0
```

**Comment by kkarkos** [comment]
What worked for was to make sure that any ports (e.g. 8000, 8888 - or whatever your using) is not used already. On mac, check ```lsof -i TCP:8000 | grep LISTEN```and kill the blocking process ```kill -9 PID_TO_KILL``` . Try to restart your app.

**Comment by erquhart** [comment]
Most of the replies here seem related to fauna - it seems the original fix was effective. If someone feels their issue is caused by the CLI, you can open a new issue and we can discuss there.

**Comment by lluishi93** [comment]
still happening here...

**Comment by lluishi93** [comment]
Still happening here...

**Comment by erezrokah** [comment]
Hi @lluishi93, do you mind opening a new issue with more information on your setup and when is the error being reported?

**Comment by bradley** [comment]
I was seeing something very similar to this, purportedly coming from something related to netlify cli:

```
/Users/<my name>/.nodenv/versions/14.7.0/lib/node_modules/netlify-cli/node_modules/netlify-redirector/lib/redirects.js:116
      throw ex;
      ^

RangeError [ERR_OUT_OF_RANGE]: The value of "err" is out of range. It must be a negative integer. Received 536870212
    at Object.getSystemErrorName (util.js:231:11)
    at exceptionWithHostPort (internal/errors.js:532:21)
    at internalConnect (net.js:922:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:429:12)
    at GetAddrInfoReqWrap.emitLookup [as callback] (net.js:1062:9)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:68:8) {
  code: 'ERR_OUT_OF_RANGE'
```

However, after a while I was able to track this issue down to being related to a [mismatch between your versions of Node and NPM](https://stackoverflow.com/questions/57995646/error-err-out-of-range-when-using-npm-install). 

BUT, in _my case_ I hadnt recently updated either of these things (and use `.node-version`, `.nvmrc`, and `package.json` files to keep these things in order)  so it was confusing why this would suddenly happen... then I remembered I had recently stopped my [Little Snitch](https://www.obdev.at/products/littlesnitch/index.html)/[LuLu](https://objective-see.com/products/lulu.html) process from allowing an outgoing request from that node version... re-allowing it stopped the issue.

**Comment by zcaceres** [comment]
+1 MacOSX netlify-cli/2.68.8 darwin-x64 node-v12.4.0

**Comment by erezrokah** [comment]
Re-opening this as it comes up in our CI too:
https://github.com/netlify/cli/pull/1702/checks?check_run_id=1664301784#step:7:330

**Comment by eduardoboucas** [comment]
Hi! We've released version 3.4.2 just now, which should fix this problem. In case someone is still experiencing it after upgrading, please reopen the issue.

Thanks! 🙌🏻

**Comment by Namyalg** [comment]
This issue still persists. I am using version 3.5.0

**Comment by erezrokah** [comment]
Hi @Namyalg can you share a reproduction scenario or a repo with this issue?

**Comment by Namyalg** [comment]
I am unable to submit a repo presently, I encountered the error when I was trying the **netlify dev** command locally. On running the command frequently it ultimately resulted in a socket hang up.

**Comment by erezrokah** [comment]
> I am unable to submit a repo presently, I encountered the error when I was trying the **netlify dev** command locally. On running the command frequently it ultimately resulted in a socket hang up.

Thanks @Namyalg. Unfortunately without a reproduction we don't have enough information to investigate.
How about your `netlify.toml`, `package.json`, the static site generator your using and the CLI version?

**Comment by Namyalg** [comment]
Yes, I can provide these details.

Namya LG

**Comment by clawfire** [comment]
Hey there, reopening since I have the error here.
Using https://github.com/clawfire/covid19-passbook-generator/ , I launch a `netlify dev` command and ... it crash with a `error while proxying request: socket hang up` even when the page isn't loaded in the browser. Meanwhile, the started server from parcel works just well.

**Comment by erezrokah** [comment]
Hi @clawfire do you mind opening a new issue for that? This might be specific to `https` or you setup.

We can link this issue for context

**Comment by clawfire** [comment]
Sure 😃

**Comment by mosesoak** [comment]
I wanted to report that I'm on Windows 10 using WSL (bridged Linux subsystem) and do get this error with all standard security settings turned on, but seemed to be able to make them go away by temporarily disabling all windows security features and restarting my machine. The errors came back after I restored security settings and rebooted. In case that helps anyone at the Netlify team figure this out.

As a side note possibly for a future issue or support ticket, I am not currently able to use `netlify dev` at all, it's mysteriously breaking just on my machine (all pages 404 with 'Not Found' shown in the browser) and not on any of my coworkers' boxes using the same repo setup. The temporary disabling of all windows security features as well as turning off all browser extensions didn't fix the 404's but did seem to make the socket hang up error disappear as noted above. I've tried a fresh repo install using the same yarn.lock as my coworkers, and tried netlify unlink/link to be sure everything's clean. The server seems to crash right when our main develop command gets run by netlify, which for the record is `yarn clean:babel && gatsby-ts develop --port 8000`. I'll pursue this separately but wanted to toss it out here in case anyone reading this has experienced it before. Thanks
